import { GlobeRTSWorld } from "./globeWorld.js";
import { FACTIONS, AGE_DATA, RESOURCE_KEYS, getFactionList } from "./factions.js";
import { FIRST_GLOBE_MAP } from "./globeMaps.js";
import { normalizeMapDefinition, exportMapJSON } from "./mapSchema.js";
import { ScenarioRuleEngine } from "./scenarioRules.js";

const $=id=>document.getElementById(id);
const ui={viewport:$("viewport"),mapTitle:$("mapTitle"),start:$("startScreen"),cards:$("factionCards"),left:$("leftHud"),right:$("rightHud"),factionName:$("factionName"),factionSpecial:$("factionSpecial"),resources:$("resources"),allocation:$("allocation"),train:$("trainButtons"),ageBtn:$("ageBtn"),siteList:$("siteList"),battleState:$("battleState"),toast:$("toast"),moveHint:$("moveHint"),loadMapBtn:$("loadMapBtn"),mapFile:$("mapFile"),restart:$("restartBtn")};
const LABEL={food:"Food",wood:"Wood",stone:"Stone",gold:"Gold"};
const ICON={food:"◆",wood:"♣",stone:"⬢",gold:"●"};
const BASE_INCOME={food:.72,wood:.64,stone:.44,gold:.42};
let activeMap=loadInitialMap();

const state={started:false,ended:false,faction:null,enemyFaction:null,resources:{food:0,wood:0,stone:0,gold:0},allocation:{food:35,wood:30,stone:15,gold:20},workforce:20,age:0,playerCapital:null,enemyCapital:null,awaitingMove:false,enemySpawn:0,enemyCommand:0,growthClock:0,hudClock:0,elapsed:0,objectives:{}};

const world=new GlobeRTSWorld(ui.viewport,{onSurfaceClick:(geo)=>handleSurfaceClick(geo),onEntityDestroyed:(entity)=>onDestroyed(entity)});
const rules=new ScenarioRuleEngine({getContext:()=>ruleContext(),performAction:(action,context)=>performRuleAction(action,context)});
world.loadMap(activeMap);ui.mapTitle.textContent=`${activeMap.name} • true spherical RTS adapter`;

function loadInitialMap(){try{const raw=localStorage.getItem("axm-rts-active-globe-map");if(raw){const map=normalizeMapDefinition(JSON.parse(raw));if(map.projection==="globe")return map;}}catch{}return FIRST_GLOBE_MAP;}
function wrapLon(value){let v=value;while(v>180)v-=360;while(v<-180)v+=360;return v;}
function nearGeo(geo,dLat=0,dLon=0){return{lat:Math.max(-88,Math.min(88,Number(geo.lat)+dLat)),lon:wrapLon(Number(geo.lon)+dLon),elevation:0};}
function costText(cost={}){return Object.entries(cost).map(([k,v])=>`${ICON[k]||""}${Math.ceil(v)}`).join(" ");}
function scaledCost(cost,m=1){return Object.fromEntries(Object.entries(cost||{}).map(([k,v])=>[k,Math.ceil(v*m)]));}
function canAfford(cost){return Object.entries(cost).every(([k,v])=>(state.resources[k]||0)>=v);}
function pay(cost){if(!canAfford(cost))return false;for(const[k,v]of Object.entries(cost))state.resources[k]-=v;return true;}
function showToast(text,kind=""){ui.toast.textContent=text;ui.toast.className=`toast ${kind}`.trim();clearTimeout(showToast.t);showToast.t=setTimeout(()=>ui.toast.classList.add("hidden"),2600);}

function renderFactionCards(){ui.cards.innerHTML="";for(const faction of getFactionList()){const b=document.createElement("button");b.className="faction-card";b.innerHTML=`<span class="symbol">${faction.symbol}</span><strong>${faction.name}</strong><small>${faction.tagline}</small><small>${faction.traits.join(" • ")}</small>`;b.onclick=()=>startGame(faction.id);ui.cards.appendChild(b);}}
function chooseEnemy(id){const ids=Object.keys(FACTIONS),i=ids.indexOf(id);return FACTIONS[ids[(i+1)%ids.length]];}

function startGame(factionId){
  state.started=true;state.ended=false;state.faction=FACTIONS[factionId];state.enemyFaction=chooseEnemy(factionId);state.resources={...state.faction.starting};delete state.resources.workforce;state.workforce=state.faction.starting.workforce;state.allocation={food:35,wood:30,stone:15,gold:20};state.age=Math.max(0,Number(activeMap.campaign?.startingAge)||0);state.awaitingMove=false;state.enemySpawn=0;state.enemyCommand=0;state.growthClock=0;state.elapsed=0;state.objectives={};
  world.loadMap(activeMap);
  state.playerCapital=world.spawnCapital(state.faction,activeMap.playerStart,false);
  world.spawnFounder(state.faction,nearGeo(activeMap.playerStart,3.2,4.2),false);
  world.spawnSquad(state.faction.units[0],state.faction,nearGeo(activeMap.playerStart,-2.7,5.4),false);
  state.enemyCapital=world.spawnCapital(state.enemyFaction,activeMap.enemyStart,true);
  world.spawnFounder(state.enemyFaction,nearGeo(activeMap.enemyStart,-3.0,-4.0),true);
  world.spawnSquad(state.enemyFaction.units[0],state.enemyFaction,nearGeo(activeMap.enemyStart,2.8,-5.2),true);
  ui.start.classList.add("hidden");ui.left.classList.remove("hidden");ui.right.classList.remove("hidden");ui.factionName.textContent=state.faction.name;ui.factionSpecial.textContent=`${state.faction.special} Planetary formations retain faction-specific runtime behavior.`;
  renderAllocation();renderTrain();renderHud();world.focusGeo(activeMap.playerStart);
  rules.load(activeMap);rules.start({map:activeMap});
  if(activeMap.campaign?.enabled&&activeMap.campaign.briefing)showToast(activeMap.campaign.briefing,"good");else showToast(`${state.faction.founder} has landed on ${activeMap.name}.`,"good");
}

function renderAllocation(){ui.allocation.innerHTML="";for(const key of RESOURCE_KEYS){const row=document.createElement("div");row.className="allocation-row";row.innerHTML=`<span>${LABEL[key]}</span><input type="range" min="5" max="70" step="5" value="${state.allocation[key]}"><output></output>`;const input=row.querySelector("input");input.oninput=()=>{state.allocation[key]=Number(input.value);updateAllocationLabels();};ui.allocation.appendChild(row);}updateAllocationLabels();}
function shares(){const total=Object.values(state.allocation).reduce((a,b)=>a+b,0)||1;return Object.fromEntries(RESOURCE_KEYS.map(k=>[k,state.allocation[k]/total]));}
function updateAllocationLabels(){const s=shares();[...ui.allocation.children].forEach((row,i)=>row.querySelector("output").textContent=`${Math.round(s[RESOURCE_KEYS[i]]*100)}%`);}

function renderTrain(){ui.train.innerHTML="";for(const def of state.faction.units){const cost=scaledCost(def.cost,state.faction.military.cost);const b=document.createElement("button");b.dataset.unit=def.id;b.innerHTML=`<b>${def.name}</b><small>${def.description} • ${costText(cost)}</small>`;b.onclick=()=>train(def);ui.train.appendChild(b);}renderAgeButton();}
function train(def){if(state.ended)return;const cost=scaledCost(def.cost,state.faction.military.cost);if(!pay(cost))return showToast("The planetary economy cannot equip that formation yet.","bad");const jitter=(world.getLiving("player","squad").length%5)*1.2;world.spawnSquad(def,state.faction,nearGeo(activeMap.playerStart,-2+jitter,5+jitter),false);showToast(`${def.name} deployed onto the planet.`,"good");renderHud();}
function renderAgeButton(){const next=AGE_DATA[state.age+1];if(!next){ui.ageBtn.textContent="Legacy Age reached";ui.ageBtn.disabled=true;return;}const penalty=state.faction?.id==="fatfrotz"?1.18:1,cost=scaledCost(next.cost,penalty);ui.ageBtn.textContent=`Advance: ${next.name} • ${costText(cost)}`;ui.ageBtn.disabled=!canAfford(cost);ui.ageBtn.onclick=()=>{if(!pay(cost))return;state.age++;state.workforce+=4;rules.emit("age.reached",{age:state.age,owner:"player"});showToast(`${next.name} reached across ${activeMap.name}.`,"good");renderHud();};}

function handleSurfaceClick(geo){if(!state.started||state.ended||!state.awaitingMove)return;world.command("player",geo);state.awaitingMove=false;ui.moveHint.classList.add("hidden");showToast(`Formation route set across the globe: ${geo.lat.toFixed(1)}°, ${geo.lon.toFixed(1)}°.`);}
function commandArmy(command){if(!state.started||state.ended)return;if(command==="move"){state.awaitingMove=true;ui.moveHint.classList.remove("hidden");return;}state.awaitingMove=false;ui.moveHint.classList.add("hidden");if(command==="defend"){world.command("player",activeMap.playerStart);world.focusGeo(activeMap.playerStart);showToast("Planetary doctrine: defend the capital.");}else if(command==="attack"){world.command("player",activeMap.enemyStart);world.focusGeo(activeMap.enemyStart);showToast("Planetary doctrine: cross-world assault.");}else if(command==="site"){const site=nextSiteFor("player");if(site){world.command("player",site.def.geo);world.focusGeo(site.def.geo);showToast(`Planetary doctrine: secure ${site.def.name}.`);}}}
function nextSiteFor(owner){const candidates=world.sites.filter(site=>site.owner!==owner);if(!candidates.length)return null;const capital=owner==="player"?state.playerCapital:state.enemyCapital;candidates.sort((a,b)=>world.surfaceDistance(capital,a)-world.surfaceDistance(capital,b));return candidates[0];}

function updateSites(dt){for(const site of world.sites){const p=world.siteUnits("player",site),e=world.siteUnits("enemy",site),contested=p>0&&e>0;let delta=0;if(!contested){if(p>0)delta=Number(site.def.captureRate||25)*Math.min(2,p)*dt;else if(e>0)delta=-Number(site.def.captureRate||25)*Math.min(2,e)*dt;else if(site.owner==="neutral"){if(site.progress>0)delta=-Math.min(site.progress,4*dt);else if(site.progress<0)delta=Math.min(-site.progress,4*dt);}}site.progress=Math.max(-100,Math.min(100,site.progress+delta));const previous=site.owner;if(site.progress>=100)site.owner="player";else if(site.progress<=-100)site.owner="enemy";else if((site.owner==="player"&&site.progress<15)||(site.owner==="enemy"&&site.progress>-15))site.owner="neutral";world.setSiteVisual(site,site.owner,site.progress,contested);if(previous!==site.owner){rules.emit("site.captured",{site:site.def,object:site.def,owner:site.owner,previous});showToast(`${site.def.name}: ${site.owner} control.`,site.owner==="player"?"good":site.owner==="enemy"?"bad":"");}}}

function economyTick(dt){const s=shares(),ageMult=AGE_DATA[state.age]?.multiplier||1;for(const key of RESOURCE_KEYS){let gain=state.workforce*s[key]*BASE_INCOME[key]*(state.faction.economy[key]||1)*ageMult*dt;for(const site of world.sites)if(site.owner==="player")gain+=(site.def.bonus?.[key]||0)*ageMult*dt;state.resources[key]+=gain;}state.growthClock+=dt;if(state.growthClock>44){state.growthClock=0;state.workforce++;showToast("Planetary population added one workforce unit.");}}

function enemyTick(dt){state.enemySpawn+=dt;state.enemyCommand+=dt;const squads=world.getLiving("enemy","squad");if(state.enemySpawn>=Math.max(11,20-state.age*2)&&squads.length<8+state.age){state.enemySpawn=0;const units=state.enemyFaction.units,def=units[Math.random()<.3?Math.min(1,units.length-1):0],j=squads.length%4;world.spawnSquad(def,state.enemyFaction,nearGeo(activeMap.enemyStart,2-j,-5-j),true);}if(state.enemyCommand>=22){state.enemyCommand=0;const site=nextSiteFor("enemy");if(site&&Math.random()<.68)world.command("enemy",site.def.geo);else world.command("enemy",activeMap.playerStart);}}

function resetFactionStats(entity){const d=entity.userData;if(d.__baseDamage===undefined)d.__baseDamage=d.damage||0;if(d.__baseSpeed===undefined)d.__baseSpeed=d.speed||0;if(d.__baseRange===undefined)d.__baseRange=d.range||0;d.damage=d.__baseDamage;d.speed=d.__baseSpeed;d.range=d.__baseRange;}
function applyFactionRuntime(owner,faction){const formations=world.getLiving(owner).filter(e=>e.userData.type==="squad"||e.userData.type==="founder");formations.forEach(resetFactionStats);const squads=formations.filter(e=>e.userData.type==="squad"),founder=formations.find(e=>e.userData.type==="founder");if(faction.id==="northpole"&&founder){for(const squad of squads)if(world.surfaceDistance(squad,founder)<=8){squad.userData.damage*=1.12;squad.userData.speed*=1.05;}}else if(faction.id==="suitcase"){for(const squad of squads)if(squad.userData.targetNormal&&squad.userData.normal.angleTo(squad.userData.targetNormal)*world.radius>4)squad.userData.speed*=1.22;}else if(faction.id==="fatfrotz"){for(const squad of squads){let n=0;for(const other of squads)if(other!==squad&&world.surfaceDistance(squad,other)<=6.5)n++;squad.userData.damage*=1+Math.min(.20,n*.05);}}else if(faction.id==="clockworkOrchard"){for(const squad of squads)if(!squad.userData.targetNormal){squad.userData.damage*=1.10;squad.userData.range+=.45;}}}

function onDestroyed(entity){rules.emit("object.destroyed",{object:{id:entity.userData.label,type:entity.userData.type,owner:entity.userData.owner,tags:[]},owner:entity.userData.owner});if(entity.userData.type==="capital")endGame(entity.userData.owner==="enemy");}
function endGame(victory){if(state.ended)return;state.ended=true;state.awaitingMove=false;ui.moveHint.classList.add("hidden");showToast(victory?(activeMap.campaign?.victoryText||"Planetary victory — opposing capital broken."):(activeMap.campaign?.defeatText||"Planetary defeat — your capital has fallen."),victory?"good":"bad");}

function ruleContext(){const objects={};for(const site of world.sites)objects[site.def.id]={alive:true,owner:site.owner,tags:site.def.tags||[]};for(const e of world.entities)objects[e.userData.label]={alive:Boolean(e.parent&&e.userData.hp>0),owner:e.userData.owner,tags:[]};return{resources:state.resources,age:state.age,factionId:state.faction?.id,owner:"player",objects,objectives:state.objectives};}
function performRuleAction(action,context){switch(action.type){case"message.show":showToast(action.text||String(action.value||"Scenario event"));break;case"resource.add":if((action.owner||"player")==="player")state.resources[action.resource||"gold"]=(state.resources[action.resource||"gold"]||0)+Number(action.value||0);break;case"resource.set":if((action.owner||"player")==="player")state.resources[action.resource||"gold"]=Number(action.value||0);break;case"object.owner":{const site=world.sites.find(s=>s.def.id===action.objectId);if(site){site.owner=action.owner||action.value||"neutral";site.progress=site.owner==="player"?100:site.owner==="enemy"?-100:0;world.setSiteVisual(site,site.owner,site.progress,false);}break;}case"spawn.formation":{const owner=action.owner||"player",faction=owner==="enemy"?state.enemyFaction:state.faction,def=faction.units.find(u=>u.id===action.id)||faction.units[0],geo=owner==="enemy"?activeMap.enemyStart:activeMap.playerStart;world.spawnSquad(def,faction,geo,owner==="enemy");break;}case"objective.complete":state.objectives[action.objectiveId||action.value]={complete:true};rules.emit("objective.completed",{objectiveId:action.objectiveId||action.value});break;case"objective.fail":state.objectives[action.objectiveId||action.value]={complete:false,failed:true};break;case"camera.focus":{const site=world.sites.find(s=>s.def.id===action.objectId);if(site)world.focusGeo(site.def.geo);break;}case"weather.set":world.scene.background.set(action.weather==="night"?0x02050b:action.weather==="storm"?0x283039:0x050b12);break;case"victory":endGame(true);break;case"defeat":endGame(false);break;default:break;}}

function renderHud(){if(!state.started)return;ui.resources.innerHTML=RESOURCE_KEYS.map(k=>`<div class="resource"><span>${ICON[k]} ${LABEL[k]}</span><strong>${Math.floor(state.resources[k])}</strong></div>`).join("");renderAgeButton();for(const b of ui.train.querySelectorAll("button[data-unit]")){const def=state.faction.units.find(x=>x.id===b.dataset.unit);b.disabled=!canAfford(scaledCost(def.cost,state.faction.military.cost));}ui.siteList.innerHTML=world.sites.map(site=>`<div class="site ${site.contested?"contested":site.owner}"><b>${site.def.name}</b><span>${site.contested?"contested":site.owner} · ${Math.abs(site.progress).toFixed(0)}%</span></div>`).join("");const pc=state.playerCapital?.parent?Math.max(0,state.playerCapital.userData.hp/state.playerCapital.userData.maxHp*100):0,ec=state.enemyCapital?.parent?Math.max(0,state.enemyCapital.userData.hp/state.enemyCapital.userData.maxHp*100):0;ui.battleState.innerHTML=`<div class="state-row"><span>Age</span><b>${AGE_DATA[state.age]?.name||state.age}</b></div><div class="state-row"><span>Workforce</span><b>${state.workforce}</b></div><div class="state-row"><span>Your formations</span><b>${world.getLiving("player","squad").length}</b></div><div class="state-row"><span>Enemy formations</span><b>${world.getLiving("enemy","squad").length}</b></div><div class="state-row"><span>Sites held</span><b>${world.sites.filter(s=>s.owner==="player").length}/${world.sites.length}</b></div><div class="state-row"><span>Your capital</span><b>${pc.toFixed(0)}%</b></div><div class="state-row"><span>Enemy capital</span><b>${ec.toFixed(0)}%</b></div>`;}

function simulate(dt){if(!state.started||state.ended)return;state.elapsed+=dt;economyTick(dt);updateSites(dt);enemyTick(dt);applyFactionRuntime("player",state.faction);applyFactionRuntime("enemy",state.enemyFaction);rules.update(dt,ruleContext());state.hudClock+=dt;if(state.hudClock>.35){state.hudClock=0;renderHud();}}

function loadMap(map){const normalized=normalizeMapDefinition(map);if(normalized.projection!=="globe")throw new Error("This runtime only accepts globe maps.");activeMap=normalized;localStorage.setItem("axm-rts-active-globe-map",exportMapJSON(activeMap));state.started=false;state.ended=false;world.loadMap(activeMap);ui.mapTitle.textContent=`${activeMap.name} • true spherical RTS adapter`;ui.start.classList.remove("hidden");ui.left.classList.add("hidden");ui.right.classList.add("hidden");showToast(`${activeMap.name} loaded.`);}

for(const button of document.querySelectorAll("[data-command]"))button.onclick=()=>commandArmy(button.dataset.command);
ui.loadMapBtn.onclick=()=>ui.mapFile.click();ui.mapFile.onchange=async()=>{const file=ui.mapFile.files?.[0];if(!file)return;try{loadMap(JSON.parse(await file.text()));}catch(error){showToast(`Map load failed: ${error.message}`,"bad");}ui.mapFile.value="";};ui.restart.onclick=()=>{if(state.faction)startGame(state.faction.id);else loadMap(activeMap);};
renderFactionCards();
let last=performance.now()/1000;function frame(ms){const now=ms/1000,dt=Math.min(.05,Math.max(0,now-last));last=now;simulate(dt);world.tick(now,dt);requestAnimationFrame(frame);}requestAnimationFrame(frame);
